### ISSUE TITLE
[BYON] Create a pipeline that would serve as a byon image import pipeline

### ISSUE THREAD

**Issue by tumido** [thoth-station/helm-charts#22]
## Problem statement
Part of: https://github.com/open-services-group/byon/issues/1
Requires: https://github.com/thoth-station/helm-charts/issues/21

## High-level Goals
Import image as imagestream

## Proposal description
A pipeline that:
1. Accepts an image url, name and description as an input parameter
2. Creates an image stream populating annotations and labels:
   ```yaml
   annotations:
     opendatahub.io/notebook-image-desc: <INPUT_DESCRIPTION>
     opendatahub.io/notebook-image-name: <INPUT_NAME>
     opendatahub.io/notebook-image-phase: Validating
     opendatahub.io/notebook-image-url: <INPUT_URL>
     opendatahub.io/notebook-image-visible: "false"
   labels:
     opendatahub.io/notebook-image: 'true'
   ```
3. At the same time it initiates validation task
4. After both tasks are completed aggregate results from validation and update the image stream with new findings:
   ```yaml
   annotations:
     opendatahub.io/notebook-image-phase: Succeeded/Failed
     opendatahub.io/notebook-image-visible: 'true'  # If succeeded
   ```
   and populate the `.spec.tags[0]` with:
   ```yaml
   name: latest
      annotations:
        opendatahub.io/notebook-python-dependencies: <DISCOVERED_PACKAGES>
        opendatahub.io/notebook-software: <PYTHON_VERSION>
        openshift.io/imported-from: <IMPORT_URL>
      from:
        kind: DockerImage
        name: <IMPORT_URL>
   ```

## Acceptance Criteria

- [ ] New pipeline resource named `byon-import-jupyterhub-image`
